### ISSUE TITLE
Elytra cape is not overridden with figura's variant

### ISSUE THREAD

**Issue by Kichura** [TotalTakeover/FiguraMerlingAvatar#25]
When wearing an elytra while the model has a custom cape file inserted, the original one is revealed instead.

**Comment by TotalTakeover** [comment]
This is because the avatar utilizes Figura's [Elytra Pivot Types](https://figura-wiki.pages.dev/enums/ModelPartParentTypes#RightElytraPivot) in an effort to save on avatar complexity and texture file size. This means that it moves the vanilla Elytra, rather than creating a fake one.

I would love to do the exact same thing for the cape, but Figura does not have that functionality. If that gets added, I plan to swap over to that instead. I would remove the cape cubes/textures from the avatar itself, and leave custom elytras/capes up to the users.
